# Generated by Django 3.0.4 on 2020-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('pub_date', models.DateTimeField(verbose_name='pub_date')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['pub_date'],
            },
        ),
    ]
